#+TITLE: bmp

Semver bumper for Emacs. Run ~bmp~ inside a project to choose the type of update
required.

For bmp to detect a /type of project/ (like poetry based), you need to write a
project /detector/ function and a class (inheriting ~bmp-project~) with a few
methods.

A detector function might look at the current ~default-directory~ and return an
instance of the new project class. For example, the node detector is the
following:

#+BEGIN_SRC emacs-lisp
  (defun bmp-node-get-project ()
    (let ((json-file "package.json"))
      (when (file-exists-p (concat default-directory json-file))
        (bmp-node-project :root-dir default-directory
                          :json-file json-file))))
#+END_SRC

Once the detector is defined, add it to the list ~bmp-project-fns~ which is walked
over by bmp sequentially.

The class for the project needs to define the following methods:

1. ~bmp-get-version-str~: Provide the current semver in the form of a string.
2. ~bmp-set-version-str~: Writes the given semver string wherever needed in the
   project.
3. ~bmp-changed-files~: Return a list of relative file paths which will be
   affected by the change of ~set-version~, used for git committing.

Take a look at one of the existing project type files to see what's happening.
